{% set name = "forcefield-utilities" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mosdef-hub/forcefield-utilities/archive/{{ version }}.tar.gz
  sha256: 27326ebf693ff9429f1543060d4548cbc4a4569e2c8c19b48953abafc7997072

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2 

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - foyer
    - gmso >=0.13
    - pydantic >=2
    - lxml

test:
  imports:
    - forcefield_utilities
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/mosdef-hub/forcefield-utilities
  summary: Utility functions and classes necessary to convert xml forcefields to foyer and gmso Forcefields
  description: |
    Utility functions and classes necessary to convert xml forcefields to foyer and gmso Forcefields
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/mosdef-hub/forcefield-utilities
  dev_url: https://github.com/mosdef-hub/forcefield-utilities

extra:
  recipe-maintainers:
    - chrisjonesBSU
    - umesh-timalsina
    - CalCraven
    - justinGilmer
    - daico007
